import React from "react";
import "./ProfileContent.css";
import { Col, Container } from "reactstrap";

const ProfileContent = () => {
  return (
    <Container fluid className="profile-content-wrapper">
      <Col className="profile-column profile-content-left">
        <div className="sticky">
          <p>Testing</p>
          <p>Testing</p>
          <p>Testing2</p>
          <img src="https://via.placeholder.com/150" alt="Sample"></img>
          <p>Testing2</p>
          <p>Testing2</p>
          <p>Testing2</p>
          <p>Testing2</p>
          <p>Testing2</p>
          <p>Testing2</p>
          <p>Testing2</p>
          <p>Testing2</p>
          <p>Testing2</p>
          <p>Testing2</p>
          <p>Testing2</p>
          <p>Testing2</p>
          <p>Testing2</p>
          <p>Testing2</p>
          <p>Testing2</p>
          <p>Testing2</p>
          <p>Testing2</p>
          <p>Testing2</p>
          <p>Testing2</p>
          <p>Testing2</p>
          <p>Testing2</p>
          <p>Testing2</p>
          <p>Testing2</p>
          <p>Testing2</p>
          <p>Testing2</p>
          <p>Testing2</p>
          <p>Testing2</p>
          <p>Testing2</p>
          <p>Testing2</p>
          <p>Testing2</p>
        </div>
      </Col>
      <Col className="profile-column profile-content-right">
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
        <p>Testing2</p>
      </Col>
    </Container>
  );
};

export default ProfileContent;
